### PR TITLE
Convert to new .csproj format for VS2017

### PR DESCRIPTION
**Pull request by k7hpn**
This PR encapsulates changes required to move from development in VS2015 to [VS2017](https://www.visualstudio.com/vs/).

If you have VS2017 installed please test this branch and let us know if there are any problems. Potential issues:

- [x] We may need to update documentation as to how to do migrations in the VS2017 environment.
- [x] `dotnet ef migrations add` seems to be problematic throwing an exception about `System.Diagnostics.DiagnosticSource`.

### CODE REVIEW

**Comment by k7hpn** [comment]
@justinmeiners is it going to mess you up if we move to VS2017?

**Comment by justinmeiners** [comment]
As long as the project files will work with the command line tools on mac (dotnet run), etc, then I am perfectly fine.

 I only use VS code as a text editor, so I am not touching any of the project files for IDE settings, building, debug, etc.

**Comment by k7hpn** [comment]
After all these years you'd think I'd know better than to be an early-adopter... :rage4:

So @justinmeiners the commandline `dotnet ef` tool is not working for me in Windows or in Mac OS with the checked-in configuration. I get a stacktrace that starts with:
```
System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```
There is a workaround in Windows: if you edit the `GRA.Data.Whatever.csproj` file and change the `<TargetFramework>` to `netcoreapp1.0` the command-line migration stuff will work. Then you can edit it back to `netcoreapp1.1` when you run. This is tedious and silly. It doesn't seem to require the `--startup-project` stuff either.

The bad news is the workaround is not working for me in Mac OS. I'd be interested to know if it works for you. I think on Mac OS editing the `.csproj` file is triggering a rebuild which fails with that `netcoreapp1.0` setting.

Based on some poking around I see aspnet/EntityFramework#7557 which seems to say it's an external problem (and provided the workaround) and I've posted in dotnet/corefx#15031 though that issue is closed. I'm not sure if we have something configured incorrectly (I don't think so, it looks like we should be using `Microsoft.EntityFrameworkCore.Tools.DotNet` v1.0.0 for the CLI tooling and `Microsoft.EntityFrameworkCore.Tools` v1.1.0 for the package reference).

**Comment by k7hpn** [comment]
Never mind. I got this working, problem was user error*. This works fine: `dotnet ef migrations add test -s ../GRA.Web`
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
*I am the user in question.

**Comment by JCorrell** [comment]
Harald, I'm confused by your resolution.  Are you saying you're no longer experiencing a problem?  Or you were able to get it working via the workaround you mentioned (editing the .csproj file)?  I'm having the same issue so I've been following with interest.

**Comment by k7hpn** [comment]
@JCorrell so the problem we were experiencing is: since our data context is in a class library there's no start point and migrations can't pull in any context information about what database to connect to, etc. In order for migrations to work we have to give it some context, so either:

- Specify a startup project that has a `Main` including database connection information (what I did to solve our problem, that's what the `-s ../GRA.Web` is for).

- [Cheat](http://benjii.me/2016/06/entity-framework-core-migrations-for-class-library-projects/) by making the class library itself have a `Main()` and include an `IDbContextFactory` with connection information.

Prior to core we were specifying a startup project with `-s` and it seemed to be looking at the `IDBContextFactory` in the class library project (I think?). Now it's showing a warning about not being able to find the context which I assume has something to do with the `IDbContextFactory` being defined in our class library and not our startup project. Migrations are working despite the warning.

The workaround did work for me but I felt like it was kind-of grody.

**Comment by justinmeiners** [comment]
@haraldnagel I appreciate you keeping me in mind for this one. I am glad it is resolved, once I finish this current feature I will merge and confirm that it is functioning properly.

**Pull request merged**
