### PR TITLE
Add dynamic avatar bundle and admin

### PR DESCRIPTION
**Pull request by justinmeiners**
This likely needs a bit more work, and may have a few bugs, but I need a review to confirm I am doing this work correctly.

Features:
- [x] Dynamic avatar is now a bundle for elements
- [x] Avatars store name and position instead of individual elements.
- [x] Dynamic avatar index page with search
- [x] Dynamic avatar edit
- [x] Dynamic avatar user front end
- [x] Element editing/image upload
- [x] Flight Control generation updated to use Dynamic Avatars
- [x] Deleting avatars deletes images
- [x] Change back startup settings to default for main project (SQLServer etc)

For Review:
- [x] Does the new avatar structure fit your needs?
- [x] Does my updated flight control work as desired?
- [x] I noticed that the DB is not using cascade anywhere. In my avatar deletion I do a sort of manual cascade. Is this acceptable?
- [x] In  "EditElement" I couldn't figure out how to validate the ModelState since it tries to validate other view model properties. I skipped checking ModelState.IsValid, is this acceptable? Is there an alternative?
- [x] When I delete an avatar I don't delete  image files, should I?
- [x] I don't allow the user to clear an element from the avatars, should I? However, they can delete entire avatars.

If you have any other recommendations let me know. I really want my contributions to be up to quality with the rest of the project. I am happy to take feedback and improve it.

### CODE REVIEW

**Comment by ghost** [comment]
Your pull request doesn't follow our guidelines. Please fix the following:

* Pull request title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/pull-request/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/MCLD/gra4/233/1b2b5cb1-0b73-465b-b80c-d039e76f7ff5/623f0fd1-1176-49c6-9800-33c948a017ed) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, the title and description now looks good! :bowtie:

**Comment by k7hpn** [comment]
This code worked great on the first try for me, yay! I haven't dug through your code yet but here are some comments on the workings operationally and responses to your questions:

> Does my updated flight control work as desired?

Looks like it worked fine to me!

> I noticed that the DB is not using cascade anywhere. In my avatar deletion I do a sort of manual cascade. Is this acceptable?

Yes. I disabled cascaded deletes because it seemed really dangerous for this application. We are handling deletes manually as you describe.

> In "EditElement" I couldn't figure out how to validate the ModelState since it tries to validate other view model properties. I skipped checking ModelState.IsValid, is this acceptable? Is there an alternative?

I'll let @iafb weigh in on this, he's way more into the `ModelState` stuff than I am at this point (I've mostly been doing back-end work).

> When I delete an avatar I don't delete image files, should I?

I think so, if they are detached from the database the files don't need to hang around.

> Does the new avatar structure fit your needs?
> I don't allow the user to clear an element from the avatars, should I? However, they can delete entire avatars.

So the only thing that's weird treating avatars as a "bundle" rather than as elements is that it's our goal to add a *lot* of default avatar elements that we plan to import from the Glitch art. @iafb has worked on a process to extract some of that artwork and we're hoping to have a lot more options for our summer reading program. It's a little weird because we may end up with more elements of one type (for example: hat or shirt) than of other types. There's also really no reason that a particular element needs to be part of a particular avatar.

The code all seems to work great, I'm not sure how exactly we'll handle it if we end up with 20 shirts but only 5 heads. That's the only concern I can see with this approach. I'm sure @iafb will weigh in with thoughts as well. I'll review the code here soon and probably have some comments there.

**Comment by justinmeiners** [comment]
I am glad it worked for you! I have found a few user side bugs that I need to fix.

Two thoughts, first, I have designed it so that it can work with individual elements. Each avatar doesn't need to have an element for each layer, there might be a bit more work I need to do there to make sure it works across the board, but that is the idea. I do understand that it is not ideal for the use case you describe. The bundle probably makes it more cumbersome to detail with lots of little pieces.

Second, if it doesn't fit your objectives you don't have to accept it into the main branch. As I discussed before a lot of my work is probably unique to Provo so I do not intend to contribute a lot of it. For Provo, this contribution is important groundwork to allow avatars to be awarded (without fussing with little pieces), and it is important for them to modify them in mission control. If you choose to go this route I would prefer if your avatar system didn't change a whole lot so I can still easily merge your updates.

**Comment by k7hpn** [comment]
As long as individual elements can be added I think we're good. Our goal is really to have a lot of elements available in the default "add dynamic avatars" capability which probably will be adding them programmatically (as the current ones are through the super-secret Flight Controller). I'm not opposed to having that initial add be in bundles. If it's an issue we can always try to improve the interface later.

Honestly, we need a Web-based admin for adding/managing avatar parts anyways. Especially as we re-implement the ability to earn avatar parts or bundles. I think this is something we want to merge.

**Comment by iafb** [comment]
> In "EditElement" I couldn't figure out how to validate the ModelState since it tries to validate other view model properties. I skipped checking ModelState.IsValid, is this acceptable? Is there an alternative?

It's totally acceptable to skip ModelState validation, especially on that action where there's not a whole lot to be validating. I generally use it as more of a convenience thing so I don't have to manually check all the fields and create the messages to return.

**Comment by justinmeiners** [comment]
@haraldnagel Sounds good to me. Tomorrow I will make another pass for bugs and make sure single elements work, and then hopefully it will be ready to go.

**Comment by justinmeiners** [comment]
@haraldnagel I did a review and tested for cases involving one element in an avatar. I fixed a few bugs and made it delete images when avatars are deleted. As far as I know it should be ready to go.

**Review by k7hpn — CHANGES_REQUESTED** [review]
This looks good to me. If you can accept my PR against your branch to fix some code formatting and add lines to the change log (feel free to edit those if you want) then I think we're good to go from my end!

**Review by iafb — CHANGES_REQUESTED** [review]
Submitted a PR to add some permission checking, apart from that it looks good!

**Comment by justinmeiners** [comment]
@haraldnagel I have all of your changes merged and squashed. I think that messed up @iafb pull request. Let me see if I can sort that out.

**Comment by justinmeiners** [comment]
@iafb I added your changes manually. Poor timing on my part. I think the correct think to do would have been to cherry pick your commit? @haraldnagel it should be ready to go.

**Review by k7hpn — APPROVED** [review]

**Review by iafb — APPROVED** [review]

**Pull request merged**
